cam_model: EquidistantCamera
cam_width: 2448        # 해상도 정보가 없으므로 수동 입력 필요
cam_height: 2048       # 해상도 정보가 없으므로 수동 입력 필요
scale: 0.25
cam_fx: 779.3398118909239
cam_fy: 776.3943622977735
cam_cx: 1229.7713752064324
cam_cy: 1027.3274517083476
k1: 0.00911858852303854      # k1
k2: -0.0030730546878690035   # k2
k3: 0.0011640135614421065    # p1
k4: -0.0006598930310642293   # p2
